/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\styles\theme\matchaTheme.ts
 * Command: astryx theme build app\styles\theme\matchaTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const matchaTheme: DefinedTheme;
