/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\styles\theme\matchaTheme.ts
 * Command: astryx theme build app\styles\theme\matchaTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import { matchaIconRegistry } from './icons';
/**
 * matcha theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { matchaTheme } from './matcha';
 *   import './matcha.css';
 */
export const matchaTheme = {
  name: 'matcha',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5625rem",
    "--font-size-2xl": "1.9375rem",
    "--font-size-3xl": "2.4375rem",
    "--font-size-4xl": "3.0625rem",
    "--font-size-5xl": "3.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4194",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.44",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2459",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2245",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2308",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "\"Bricolage Grotesque\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#5a6b2a, #a8bf6a)",
    "--color-syntax-string": "light-dark(#2e6b4a, #7bc49e)",
    "--color-syntax-comment": "light-dark(#707E46, #707E46)",
    "--color-syntax-number": "light-dark(#8c6b30, #d4b870)",
    "--color-syntax-function": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-syntax-type": "light-dark(#6b4a8c, #b08ed4)",
    "--color-syntax-variable": "light-dark(#3E481D, #C0CBA9)",
    "--color-syntax-operator": "light-dark(#707E46, #94a468)",
    "--color-syntax-constant": "light-dark(#8c6b30, #d4b870)",
    "--color-syntax-tag": "light-dark(#8c3a3a, #d47a7a)",
    "--color-syntax-attribute": "light-dark(#7c5e3a, #c4a882)",
    "--color-syntax-property": "light-dark(#3a7c6b, #70c4b0)",
    "--color-syntax-punctuation": "light-dark(#566a39, #92af6a)",
    "--color-syntax-background": "light-dark(#F0F0E0, #1a1c14)",
    "--color-accent": "light-dark(#1f4037, #8fc4b0)",
    "--color-accent-muted": "light-dark(#3E481D14, #C0CBA920)",
    "--color-neutral": "light-dark(#3E481D0F, #C0CBA91A)",
    "--color-background-surface": "light-dark(#FFFFFF, #1a1c14)",
    "--color-background-body": "light-dark(#F0F0E0, #12140e)",
    "--color-overlay": "light-dark(#3E481D80, #3E481DCC)",
    "--color-overlay-hover": "light-dark(#3E481D0D, #C0CBA90D)",
    "--color-overlay-pressed": "light-dark(#3E481D1A, #C0CBA91A)",
    "--color-background-muted": "light-dark(#F0F0E0, #3E481D)",
    "--color-text-primary": "light-dark(#3E481D, #C0CBA9)",
    "--color-text-secondary": "light-dark(#707E46, #94a468)",
    "--color-text-disabled": "light-dark(#C0CBA9, #5a6440)",
    "--color-text-accent": "light-dark(#3E481D, #C0CBA9)",
    "--color-on-dark": "#FFFFFF",
    "--color-on-light": "#3E481D",
    "--color-on-accent": "light-dark(#FFFFFF, #3E481D)",
    "--color-on-success": "light-dark(#FFFFFF, #3E481D)",
    "--color-on-error": "light-dark(#FFFFFF, #3E481D)",
    "--color-on-warning": "light-dark(#3E481D, #3E481D)",
    "--color-icon-accent": "light-dark(#3E481D, #C0CBA9)",
    "--color-icon-primary": "light-dark(#3E481D, #C0CBA9)",
    "--color-icon-secondary": "light-dark(#707E46, #94a468)",
    "--color-icon-disabled": "light-dark(#C0CBA9, #5a6440)",
    "--color-background-card": "light-dark(#FFFFFF, #1e2016)",
    "--color-background-popover": "light-dark(#FFFFFF, #3E481D)",
    "--color-background-inverted": "light-dark(#3E481D, #C0CBA9)",
    "--color-success": "light-dark(#4D9900, #6dbf2a)",
    "--color-success-muted": "light-dark(#4D990020, #6dbf2a20)",
    "--color-error": "light-dark(#8a2f2f, #e08585)",
    "--color-error-muted": "light-dark(#8a2f2f18, #e0858520)",
    "--color-warning": "light-dark(#FFB600, #ffc940)",
    "--color-warning-muted": "light-dark(#FFB60020, #ffc94020)",
    "--color-border": "light-dark(#DCE3CE, #C0CBA91A)",
    "--color-border-emphasized": "light-dark(#B7C29E, #5a6440)",
    "--color-skeleton": "light-dark(#C0CBA9, #5a6440)",
    "--color-shadow": "light-dark(#3E481D1A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#3a5e8c33, #3a5e8c33)",
    "--color-border-blue": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-icon-blue": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-text-blue": "light-dark(#2e4a6e, #8dbce0)",
    "--color-background-cyan": "light-dark(#3a7c7c33, #3a7c7c33)",
    "--color-border-cyan": "light-dark(#3a7c7c, #70c4c4)",
    "--color-icon-cyan": "light-dark(#3a7c7c, #70c4c4)",
    "--color-text-cyan": "light-dark(#2e6060, #82d4d4)",
    "--color-background-gray": "light-dark(#707E4633, #5a644033)",
    "--color-border-gray": "light-dark(#707E46, #707E46)",
    "--color-icon-gray": "light-dark(#707E46, #94a468)",
    "--color-text-gray": "light-dark(#3E481D, #C0CBA9)",
    "--color-background-green": "light-dark(#4D990033, #6dbf2a33)",
    "--color-border-green": "light-dark(#4D9900, #6dbf2a)",
    "--color-icon-green": "light-dark(#4D9900, #6dbf2a)",
    "--color-text-green": "light-dark(#3d7a00, #80d43a)",
    "--color-background-orange": "light-dark(#c4762033, #d4903a33)",
    "--color-border-orange": "light-dark(#c47620, #d4903a)",
    "--color-icon-orange": "light-dark(#c47620, #d4903a)",
    "--color-text-orange": "light-dark(#a06018, #e0a04a)",
    "--color-background-pink": "light-dark(#c44a7033, #e07a9a33)",
    "--color-border-pink": "light-dark(#c44a70, #e07a9a)",
    "--color-icon-pink": "light-dark(#c44a70, #e07a9a)",
    "--color-text-pink": "light-dark(#a03a5a, #f08aaa)",
    "--color-background-purple": "light-dark(#6b4a8c33, #b08ed433)",
    "--color-border-purple": "light-dark(#6b4a8c, #b08ed4)",
    "--color-icon-purple": "light-dark(#6b4a8c, #b08ed4)",
    "--color-text-purple": "light-dark(#553a70, #c0a0e0)",
    "--color-background-red": "light-dark(#FD000033, #ff5c5c33)",
    "--color-border-red": "light-dark(#FD0000, #ff5c5c)",
    "--color-icon-red": "light-dark(#FD0000, #ff5c5c)",
    "--color-text-red": "light-dark(#cc0000, #ff7a7a)",
    "--color-background-teal": "light-dark(#2e6b5a33, #5ab89833)",
    "--color-border-teal": "light-dark(#2e6b5a, #5ab898)",
    "--color-icon-teal": "light-dark(#2e6b5a, #5ab898)",
    "--color-text-teal": "light-dark(#245546, #6ccaaa)",
    "--color-background-yellow": "light-dark(#FFB60033, #ffc94033)",
    "--color-border-yellow": "light-dark(#FFB600, #ffc940)",
    "--color-icon-yellow": "light-dark(#FFB600, #ffc940)",
    "--color-text-yellow": "light-dark(#cc9200, #ffd960)",
    "--spacing-0-5": "3px",
    "--spacing-1": "6px",
    "--spacing-1-5": "9px",
    "--spacing-2": "12px",
    "--spacing-3": "18px",
    "--spacing-4": "24px",
    "--spacing-5": "30px",
    "--spacing-6": "36px",
    "--spacing-7": "42px",
    "--spacing-8": "48px",
    "--spacing-9": "54px",
    "--spacing-10": "60px",
    "--spacing-11": "66px",
    "--spacing-12": "72px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--size-element-sm": "36px",
    "--size-element-md": "40px",
    "--size-element-lg": "44px",
    "--shadow-low": "0 2px 4px #3E481D0D, 0 4px 8px #3E481D1A",
    "--shadow-med": "0 2px 4px #3E481D0D, 0 4px 12px #3E481D1A",
    "--shadow-high": "0 4px 6px #3E481D1A, 0 12px 24px #3E481D26",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #3E481D30",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #3E481D50",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #4D990050",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #FFB60050",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #FD000050"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-page)",
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: matchaIconRegistry,
};

export { matchaIconRegistry };
